version: "3.8"

networks:
  portal_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  slc-tech:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    networks:
        portal_network:
            ipv4_address: 172.20.0.3
    volumes:
      - ./web:/src
    ports:
      - 1313:1313
