services:
  slc-tech-build:
    build:
      context: ./web
      args:
        - ENV=production
    volumes:
      - ./web:/src
      - slc-tech-vol:/dist

  slc-tech:
    image: nginx:alpine
    volumes:
      - slc-tech-vol:/usr/share/nginx/html
    # ports:
    #   - 80:80
    depends_on:
      slc-tech-build:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  slc-tech-vol:

