############# English navigation ##############

# main menu
#[[main]]
#name = "Home"
#pageRef = "/"
#weight = 1

[[main]]
name = "Home"
pageRef = "/"
weight = 2

#[[main]]
#name = "Elements"
#pageRef = "/elements"
#weight = 3

#[[main]]
#weight = 4
#name = "Pages"

[[main]]
name = "Members"
pageRef = "/members"
weight = 3

[[main]]
name = "Documentation"
url = "https://slc-docs.iiit.ac.in/"
weight = 4
[main.params]
    external = true
    newTab = true

[[main]]
name = "Updates"
pageRef = "/updates"
weight = 5

[[main]]
name = "Projects"
pageRef = "/Projects"
weight = 5

#[[main]]
#name = "Contact"
#pageRef = "/contact"
#weight = 3

#[[main]]
#parent = "Pages"
#name = "Categories"
#pageRef = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


## footer menu
#[[footer]]
#name = "About"
#pageRef = "/about"
#weight = 1

#[[footer]]
#name = "Elements"
#pageRef = "/elements"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#pageRef = "/privacy-policy"
